import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"

const alaska = localFont({
  src: [

    {
      path: "../public/fonts/AlasTrial-Light.otf",
      weight: "300",
      style: "normal"
    },
    {
      path: "../public/fonts/AlasTrial-Regular.otf",
      weight: "400",
      style: "normal"
    },
    {
      path: "../public/fonts/AlasTrial-Medium.otf",
      weight: "500",
      style: "normal"
    },
    {
      path: "../public/fonts/AlasTrial-Bold.otf",
      weight: "600",
      style: "normal"
    },

  ]
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${alaska.className}`}>{children}</body>
    </html>
  );
}
